### ISSUE TITLE
Typo in syncToPrevList?

### ISSUE THREAD

**Issue by DanAndersen** [Adam4lexander/UnityObservables#1]
Hi,
Thanks for putting this code together -- I had a quick observation:

https://github.com/Adam4lexander/UnityObservables/blob/8244c6e46d9cb7ebad7423a274c6d4571cafcffa/Assets/UnityObservables/ObservableList.cs#L166

From the comment and some initial testing, I think it might need to be:
```
if (!Application.isEditor) {
    return;
}
```

**Comment by Adam4lexander** [comment]
Youre right, thanks for letting me know!
